// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Comment struct {
	Commentid    uuid.UUID
	Content      sql.NullString
	Lastmodified sql.NullTime
	Isedited     sql.NullBool
	Upvotes      int32
	Downvotes    int32
	Userid       uuid.NullUUID
	Postid       uuid.NullUUID
}

type Post struct {
	Postid       uuid.UUID
	Title        string
	Content      sql.NullString
	Lastmodified sql.NullTime
	Isedited     sql.NullBool
	Upvotes      sql.NullInt32
	Downvotes    sql.NullInt32
	Userid       uuid.NullUUID
}

type User struct {
	Userid       uuid.UUID
	Name         string
	Lastmodified sql.NullTime
	Password     string
}
