// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (UserID, Name, LastModified, Password)
VALUES ($1, $2, $3, $4)
RETURNING userid, name, lastmodified, password
`

type CreateUserParams struct {
	Userid       uuid.UUID
	Name         string
	Lastmodified sql.NullTime
	Password     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Userid,
		arg.Name,
		arg.Lastmodified,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Name,
		&i.Lastmodified,
		&i.Password,
	)
	return i, err
}
